name: PR Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  detect_deployment_type:
    name: Detect Deployment Type
    runs-on: ubuntu-latest
    outputs:
      deployment_type: ${{ steps.set_deployment_type.outputs.deployment_type }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect Deployment Type from Branch Name
        id: set_deployment_type
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Source branch: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" == feature/ota/* ]]; then
            echo "deployment_type=ota" >> $GITHUB_ENV
            echo "deployment_type=ota" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH_NAME" == feature/build/* ]]; then
            echo "deployment_type=build" >> $GITHUB_ENV
            echo "deployment_type=build" >> $GITHUB_OUTPUT
          else
            echo "deployment_type=none" >> $GITHUB_ENV
            echo "deployment_type=none" >> $GITHUB_OUTPUT
          fi

  deploy_ota:
    name: OTA Update
    needs: detect_deployment_type
    runs-on: ubuntu-latest
    if: needs.detect_deployment_type.outputs.deployment_type == 'ota'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Deploy OTA Update
        run: |
          eas update --auto --branch pr-${{ github.event.number }}
      
      - name: Generate QR Code for Expo Go
        run: |
          QR_CODE_URL="https://expo.dev/update/pr-${{ github.event.number }}"
          echo "Scan this QR code to test: $QR_CODE_URL"
          echo "$QR_CODE_URL" | qrencode -o qrcode.png
          
      - name: Upload QR Code
        uses: actions/upload-artifact@v4
        with:
          name: expo-qr-code
          path: qrcode.png

      - name: Comment QR Code on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "🚀 **Preview Ready!** Scan this QR code with Expo Go to test: ![QR Code](https://github.com/${{ github.repository }}/actions/artifacts/${{ github.run_id }}/expo-qr-code/qrcode.png)"

  deploy_build:
    name: Full Build
    needs: detect_deployment_type
    runs-on: ubuntu-latest
    if: needs.detect_deployment_type.outputs.deployment_type == 'build'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build App
        run: |
          eas build --platform all --profile preview --non-interactive

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: eas-build
          path: build-output/
