name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - staging
      - main

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: source/yarn.lock

      - name: Install dependencies
        working-directory: source
        run: yarn install --frozen-lockfile

      - name: Run ESLint (Check Mode)
        working-directory: source
        run: yarn eslint .

  detect_deployment_type:
    name: Detect Deployment Type
    runs-on: ubuntu-latest
    needs: lint
    outputs:
      deployment_type: ${{ steps.set_deployment_type.outputs.deployment_type }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch PR Title
        id: set_deployment_type
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "PR Title: $PR_TITLE"
          PR_TITLE_LOWER=$(echo "$PR_TITLE" | tr '[:upper:]' '[:lower:]')

          if [[ "$PR_TITLE_LOWER" == *"[ota]"* ]]; then
            echo "deployment_type=ota" >> $GITHUB_ENV
            echo "Detected OTA Update"
          elif [[ "$PR_TITLE_LOWER" == *"[build]"* ]]; then
            echo "deployment_type=build" >> $GITHUB_ENV
            echo "Detected Full Build"
          else
            echo "deployment_type=none" >> $GITHUB_ENV
            echo "No deployment triggered"
          fi


  deploy_ota:
    needs: detect_deployment_type
    runs-on: ubuntu-latest
    if: needs.detect_deployment_type.outputs.deployment_type == 'ota' && github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy OTA Update
        run: eas update --branch develop --message "Auto-deploy from GitHub Actions"

  deploy_build:
    needs: detect_deployment_type
    runs-on: ubuntu-latest
    if: needs.detect_deployment_type.outputs.deployment_type == 'build' && github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main')
    steps:
      - name: Build App for Staging
        if: github.ref == 'refs/heads/staging'
        run: eas build --profile preview --platform all

      - name: Build App for Production
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: eas build --profile production --platform all
