name: Manual Expo Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'android'
        type: choice
        options:
          - android
          - ios
          - both
      build_type:
        description: 'Type of deployment'
        required: true
        default: 'ota'
        type: choice
        options:
          - ota
          - build
      app_version:
        description: 'Optional app version override'
        required: false

jobs:
  build:
    name: Manual Expo Deploy
    runs-on: ubuntu-latest
    env:
      ENV: staging
      EXPO_PUBLIC_STAGING_API_BASE_URL: https://api-staging.reats.net
      EXPO_PUBLIC_STAGING_API_KEY: ${{ secrets.EXPO_PUBLIC_STAGING_API_KEY }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      EXPO_TOKEN: ${{ secrets.EXPO_STAGING_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: source/yarn.lock

      - name: Install dependencies
        working-directory: source
        run: yarn install --frozen-lockfile

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_STAGING_TOKEN }}

      - name: Run OTA update
        if: ${{ github.event.inputs.build_type == 'ota' }}
        working-directory: source
        run: eas update --auto --branch staging

      - name: Build Android
        if: ${{ github.event.inputs.build_type == 'build' && (github.event.inputs.platform == 'android' || github.event.inputs.platform == 'both') }}
        working-directory: source
        run: |
          eas build --platform android --profile preview --non-interactive --json > android_build.json
          echo "ANDROID_BUILD_ID=$(jq -r '.[0].id' android_build.json)" >> $GITHUB_ENV

      - name: Submit Android App
        if: ${{ github.event.inputs.build_type == 'build' && (github.event.inputs.platform == 'android' || github.event.inputs.platform == 'both') }}
        working-directory: source
        run: eas submit --platform android --profile preview --non-interactive --id $ANDROID_BUILD_ID

      - name: Build iOS
        if: ${{ github.event.inputs.build_type == 'build' && (github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'both') }}
        working-directory: source
        run: |
          eas build --platform ios --profile testflight --non-interactive --json > ios_build.json
          echo "IOS_BUILD_ID=$(jq -r '.[0].id' ios_build.json)" >> $GITHUB_ENV

      - name: Submit iOS App
        if: ${{ github.event.inputs.build_type == 'build' && (github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'both') }}
        working-directory: source
        run: eas submit --platform ios --profile testflight --non-interactive --id $IOS_BUILD_ID
