name: PR CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read  # Allows reading repo contents

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: source/yarn.lock

      - name: Install dependencies
        working-directory: source
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        working-directory: source
        run: yarn eslint .
